chore: switch coreos testing to 41
ublue-os/kernel-cache pull request #33
Opened 2024-10-28 19:27 UTC by RoyalOughtness

https://builds.coreos.fedoraproject.org/browser?stream=testing&arch=x86_64

2024-10-28 21:25 UTC, bsherman commented
This needs a corresponding akmods PR

2024-10-28 21:28 UTC, m2Giles approved these changes

2024-10-28 21:30 UTC, bsherman requested changes
Can't merge until 
1) akmods has a coresponding PR
2) upstream images are on 41 <https://quay.io/repository/fedora/fedora-coreos?tab=tags&tag=testing>

2024-10-29 21:10 UTC, bsherman commented
```
skopeo inspect docker://quay.io/fedora/fedora-coreos:testing|jq '.Labels."ostree.linux"'
"6.11.5-300.fc41.x86_64"
```

2024-10-29 21:10 UTC, bsherman approved these changes

2024-10-29 21:16 UTC, merged